In [2]:
import torch

In [2]:
torch.__version__

'2.7.1+rocm6.3'

In [6]:
torch.cuda.current_device()  #watch -n 1  rocm-smi

0

In [7]:
torch.cuda.get_device_name(0)

'Radeon RX 7900 XTX'

In [3]:
torch.get_default_device() #获取默认device

device(type='cpu')

In [4]:
torch.set_default_device('cuda') #设置默认device为gpu

In [6]:
torch.get_default_device()

device(type='cuda', index=0)

# tensor基本操作
<font color='green'>
每一个tensor都有dtype，device，layout三种属性。device表示该tensor存储在那个设备中，layout表示tensor在内存布局的对象
</font>

In [8]:
x=torch.tensor([5.5,2])
print(x)
x=torch.empty(5,3)
print(x)
x=torch.zeros(5,3,dtype=torch.long)
print(x)
x=x.new_ones(5,3,dtype=torch.double)
x=torch.ones(5,3,dtype=torch.double)
print(x)
x=torch.randn_like(x)
print(x)

tensor([5.5000, 2.0000])
tensor([[0.3573, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1831, -0.0216, -1.9502],
        [-0.3582,  0.2187, -0.4359],
        [ 0.5930, -0.7271, -0.5372],
        [ 0.1602,  2.5634, -0.4324],
        [ 0.4561,  0.3992, -0.9949]], dtype=torch.float64)


In [10]:
x.size()

torch.Size([5, 3])

In [12]:
x.device

device(type='cpu')

In [23]:
y=torch.rand(5,3)
x+y #或者torch.add(x,y)

tensor([[-0.1562,  0.2660, -1.3064],
        [-0.1256,  0.8436, -0.3159],
        [ 0.8157, -0.6586,  0.3919],
        [ 0.1757,  3.5402,  0.0435],
        [ 0.4583,  1.2219, -0.7107]], dtype=torch.float64)

In [16]:
x[:,-1] #索引

tensor([0.2086, 0.1287, 0.6981, 0.8484])

In [19]:
device=torch.device('cuda')
device

device(type='cuda')

In [20]:
indices=torch.tensor([[1,0,1],[0,2,2]])  #表示每一维非0元素所在index，一一对应组成非0坐标
values=torch.tensor([1,2,3],dtype=torch.float32)  #非0元素的值，和indices坐标对因
sparse_tensor=torch.sparse_coo_tensor(indices,values,[2,4],device=device) #创建稀疏tensor. [2,4]表示tensor的shape
sparse_tensor

tensor(indices=tensor([[1, 0, 1],
                       [0, 2, 2]]),
       values=tensor([1., 2., 3.]),
       device='cuda:0', size=(2, 4), nnz=3, layout=torch.sparse_coo)

In [21]:
sparse_tensor.to_dense()  #转为稠密矩阵

tensor([[0., 0., 2., 0.],
        [1., 0., 3., 0.]], device='cuda:0')

## 基本运算

In [42]:
x+y #或者torch.add(x,y)
x-y #或者torch.sub(x,y)
x * y #对应元素乘积。或者torch.mul(x,y) 
x / y #对应元素。或者torch.div(x,y) 

z=y.view(3,5)
z=z.type(torch.float64)
x @ z #矩阵点积。或者的torch.mm(x,z), x.mm(z)，x.matmul(z)等
x ** 2 # x.pow(2)
torch.exp(x) #自然常数e的x次方
x.sqrt() #开方。负值开方会转为nan
torch.log(x) #底数为e
torch.log2(x)
torch.log10(x)

tensor([[    nan,     nan,     nan],
        [    nan, -0.6601,     nan],
        [-0.2270,     nan,     nan],
        [-0.7953,  0.4088,     nan],
        [-0.3409, -0.3988,     nan]], dtype=torch.float64)

## 常用操作

In [64]:
x.floor() #向下取整
x.ceil() #向上取整
x.round() #四舍五入
x.trunc() #截取整数部分
x.frac() #截取小数部分
x % 2 #取余

tensor([[1.8169, 1.9784, 0.0498],
        [1.6418, 0.2187, 1.5641],
        [0.5930, 1.2729, 1.4628],
        [0.1602, 0.5634, 1.5676],
        [0.4561, 0.3992, 1.0051]], dtype=torch.float64)

## 比较运算：返回bool tensor

In [82]:
torch.gt(x,y)
torch.ge(x,y) #great and equal
torch.lt(x,y)
torch.le(x,y) #less and equal
torch.ne(x,y) #not equal
torch.eq(x,y) #equal

torch.sort(x, dim=1, descending=False,out=None)
torch.topk(x, 2, dim=1, largest=False,sorted=True,out=None)  #某个维度上的topn
torch.kthvalue(x,2,dim=0,out=None)  #某个维度上第k个最小值和索引

torch.return_types.kthvalue(
values=tensor([-0.1831, -0.0216, -0.9949], dtype=torch.float64),
indices=tensor([0, 0, 4]))

In [86]:
torch.isnan(x)
torch.isfinite(x) #是否有界
torch.isinf(x/0) #是否无界

tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])

## 三角函数:有很多，不一一列举

In [88]:
torch.sin(x) 
torch.tanh(x) #关于e的激活函数，类似sigmoid

tensor([[-0.1811, -0.0216, -0.9603],
        [-0.3436,  0.2153, -0.4102],
        [ 0.5320, -0.6213, -0.4909],
        [ 0.1589,  0.9882, -0.4073],
        [ 0.4269,  0.3793, -0.7594]], dtype=torch.float64)

### tanh函数验证

In [90]:
import numpy as np
(np.exp(-0.1831) - np.exp(0.1831)) / (np.exp(-0.1831) + np.exp(0.1831))

-0.18108089267529975

## 其他常用函数

In [92]:
torch.sigmoid(x)
torch.abs(x)
torch.sign(x)  #符号函数，大于0则为1,小于0则为-1,等于0为0

tensor([[-1., -1., -1.],
        [-1.,  1., -1.],
        [ 1., -1., -1.],
        [ 1.,  1., -1.],
        [ 1.,  1., -1.]], dtype=torch.float64)

## 统计学相关函数

In [102]:
torch.mean(x)
torch.sum(x)
torch.max(x)
torch.min(x)

torch.std(x)
torch.var(x) #方差
torch.median(x) #中位数
torch.mode(x) #众数
torch.histc(x) #计算直方图
# b1=torch.bincount(x) #每个值的频数，只对1维的非负整数tensor有用

torch.argmax(x)
m1=torch.argmin(x)
p = torch.prod(x) # 全部元素的乘积

m1,p

(tensor(2), tensor(-1.9648e-06, dtype=torch.float64))

## 右对齐: 即使两个tensor维度不一致，只要最内层维度相等或者其中为1,也可以进行计算
<font color='green'>
注意维度：转为列表后，先后维度大小分别对应列表中从外到内的数量
</font>

In [48]:
a1=torch.randn(3,2,2)
a1

tensor([[[-2.2479, -0.9599],
         [ 0.9737, -1.9030]],

        [[ 0.8356, -0.5534],
         [-1.6972,  1.4734]],

        [[-0.9794, -0.7068],
         [-0.2122, -0.3974]]])

In [50]:
a2=torch.randn(2)
a2

tensor([-1.1678,  0.2560])

<font color='green'>
右对齐：实际要求最内层（也就是最后）的维度大小必须相同或者其中为1. 这样如果维度为1,则视为加上一个数值，如果维度相同则分别相加
</font>

In [51]:
a1+a2

tensor([[[-3.4157, -0.7039],
         [-0.1941, -1.6469]],

        [[-0.3322, -0.2973],
         [-2.8650,  1.7295]],

        [[-2.1472, -0.4508],
         [-1.3800, -0.1414]]])

In [55]:
a3=torch.randn(3,2,1)
a3

tensor([[[-1.7500],
         [ 0.3434]],

        [[ 1.0511],
         [ 0.7749]],

        [[ 1.1228],
         [-0.7622]]])

In [56]:
a3 + a2

tensor([[[-2.9178, -1.4940],
         [-0.8244,  0.5994]],

        [[-0.1167,  1.3072],
         [-0.3929,  1.0309]],

        [[-0.0450,  1.3789],
         [-1.9300, -0.5062]]])

In [58]:
-1.7500 + 0.2560

-1.494

## 改变tensor维度

In [17]:
x=torch.rand(4,4)
z=x.view(16) #拉平为一维
z=x.view(-1,8)  #-1表示自行计算该维度大小，满足其他维度要求即可

## 与numpy协同

In [21]:
import numpy as np
arr_np=x.numpy()
print(arr_np)
a=np.random.random((3, 2))
arr_torch=torch.from_numpy(a)
print(arr_torch)

[[-0.79082348  0.46702956  0.4503492 ]
 [-2.49619099  1.10459259 -1.58573975]
 [ 1.46363101  0.85033187  0.15847309]
 [ 1.70128043  0.62505114 -0.82194087]
 [-1.00945891  0.12987659 -0.74941647]]
tensor([[0.9551, 0.0129],
        [0.4430, 0.4704],
        [0.4062, 0.5656]], dtype=torch.float64)


# 反向传播

In [6]:
x=torch.randn([3,4],requires_grad=True)
x

tensor([[ 1.8220, -1.0967,  0.1172, -1.4547],
        [ 0.4122, -0.6556,  0.0667,  0.2554],
        [ 0.4512, -0.8796, -1.3606, -1.1600]], requires_grad=True)

In [7]:
y=torch.randn([3,4],requires_grad=True)
y

tensor([[-0.1360, -0.5001,  1.0985,  0.1350],
        [ 0.1725, -0.8531, -0.6697, -0.2645],
        [-0.9005,  0.4543, -0.5659,  0.6688]], requires_grad=True)

In [9]:
z= x + y ** 2
z

tensor([[ 1.8405, -0.8466,  1.3239, -1.4364],
        [ 0.4420,  0.0722,  0.5153,  0.3254],
        [ 1.2622, -0.6732, -1.0403, -0.7128]], grad_fn=<AddBackward0>)

In [12]:
a=torch.randn([3,4],requires_grad=True)
a

tensor([[-0.4387,  0.0649, -0.8627,  0.3155],
        [-0.1847, -0.2194, -0.5270,  0.0708],
        [ 0.7613, -0.9565, -0.5161,  0.6252]], requires_grad=True)

In [16]:
b = torch.sigmoid(z) + torch.sigmoid(a)
b

tensor([[1.2550, 0.8164, 1.0866, 0.7703],
        [1.0627, 0.9634, 0.9973, 1.0983],
        [1.4610, 0.6154, 0.6348, 0.9804]], grad_fn=<AddBackward0>)

In [17]:
result = b.sum()
result

tensor(11.7417, grad_fn=<SumBackward0>)

<font color='green'>
<h2>反向传播</h2>
1. 调用backward方法，持续调用会梯度累计。<br />
2. 梯度传播公式f(g(x))=f'(g) * g'(x).
</font>

In [18]:
result.backward()

<font color='green'>
3. result对x的梯度经过 result 对 z的梯度，又z对x的梯度传播。result 对 z的梯度 是sigmoid的梯度，z对x的梯度是 1 <br />
4. 因此x的梯度等于result关于z的梯度 乘与 z关于x的梯度1
</font>

In [19]:
x.grad

tensor([[0.1182, 0.2101, 0.1660, 0.1552],
        [0.2382, 0.2497, 0.2341, 0.2435],
        [0.1719, 0.2237, 0.1929, 0.2208]])

<font color='green'>
5. sigmoid函数的导数,a是单层函数，没有经过其他层传播
</font>

In [22]:
a.grad

tensor([[0.2383, 0.2497, 0.2087, 0.2439],
        [0.2479, 0.2470, 0.2334, 0.2497],
        [0.2170, 0.2005, 0.2341, 0.2271]])

<font color='green'>
6. y的梯度等于f'(z) * z'(y). 其中f'(z)是sigmoid函数对z值的导数，z'(y)是z= x + y ** 2中对的偏导数2y. 根据具体的z值求出f'(z)和2y求出z'(y)，相乘既是y的梯度
</font>

In [30]:
y.grad

tensor([[-0.0321, -0.2101,  0.3647,  0.0419],
        [ 0.0822, -0.4260, -0.3136, -0.1288],
        [-0.3097,  0.2032, -0.2184,  0.2953]])

In [21]:
t=[[1.2550, 0.8164, 1.0866, 0.7703],
        [1.0627, 0.9634, 0.9973, 1.0983],
        [1.4610, 0.6154, 0.6348, 0.9804]]
sum([sum(i) for i in t])

11.7416

In [27]:
torch.sigmoid(z)

tensor([[0.8630, 0.3002, 0.7898, 0.1921],
        [0.6087, 0.5181, 0.6260, 0.5806],
        [0.7794, 0.3378, 0.2611, 0.3290]], grad_fn=<SigmoidBackward0>)

In [32]:
0.8630 *( 1-0.8630)

0.118231

In [34]:
0.118231* 2 * 0.1360

0.032158832000000005