In [1]:
import torch

In [2]:
torch.cuda.get_device_name(0)

'Radeon RX 7900 XTX'

In [14]:
torch.manual_seed(1)#定义随机种子，可以在分布抽样或生成随机数时保持在一致
torch.randn(5,3)  #必须和随机种子写在一起，否则还是会变化

tensor([[ 0.6614,  0.2669,  0.0617],
        [ 0.6213, -0.4519, -0.1661],
        [-1.5228,  0.3817, -1.0276],
        [-0.5631, -0.8923, -0.0583],
        [-0.1955, -0.9656,  0.4224]])

In [15]:
torch.randn(5,3)

tensor([[ 0.2673, -0.4212, -0.5107],
        [-1.5727, -0.1232,  3.5870],
        [-1.8313,  1.5987, -1.2770],
        [ 0.3255, -0.4791,  1.3790],
        [ 2.5286,  0.4107, -0.9880]])

## 一、统计分布

In [16]:
from torch.distributions import Normal

In [32]:
torch.manual_seed(1)
dist=Normal(loc=0,scale=1)  #正太分布，distributions中有很多种分布，不一一列举
sample=dist.sample((3,))  #随机采样。输入维度数量
log_prob=dist.log_prob(sample)  #计算对数概率
sample,log_prob

(tensor([0.6614, 0.2669, 0.0617]), tensor([-1.1376, -0.9546, -0.9208]))

In [33]:
torch.dist(sample,log_prob,p=2) #计算p范数。p=1是曼哈顿距离，2是欧式距离2范数

tensor(2.3862)

In [37]:
torch.sum((sample-log_prob)**2).sqrt()

tensor(2.3862)

In [39]:
torch.norm(sample) #直接计算某个tensor的2范数。对元数值的平方和进行开方

tensor(0.7158)

In [40]:
torch.sum((sample)**2).sqrt()

tensor(0.7158)

## 二、矩阵分解
常用分解包含lu分解，qr分解，pca分解，svd分解

In [3]:
x=torch.randn(5,5)
x

tensor([[ 1.8057,  0.4287,  1.4439,  0.0571, -3.2102],
        [ 1.4465,  0.1977,  0.1997,  0.4035, -1.2453],
        [-0.2037, -0.9814,  0.8128, -0.6024, -1.4771],
        [-0.7645, -1.4458,  1.4004, -1.6750,  0.3113],
        [-1.7193, -0.5629, -0.5193, -1.5596,  0.2165]])

In [45]:
P, L, U = torch.linalg.lu(x)
P, L, U

(tensor([[0., 0., 0., 1., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 1.],
         [1., 0., 0., 0., 0.]]),
 tensor([[ 1.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.7242,  1.0000,  0.0000,  0.0000,  0.0000],
         [-0.7335,  0.2458,  1.0000,  0.0000,  0.0000],
         [ 0.3388,  0.0177,  0.0381,  1.0000,  0.0000],
         [-0.3148,  0.0664,  0.9485,  0.7414,  1.0000]]),
 tensor([[ 1.6089,  0.0938, -1.2597,  0.2546, -0.5020],
         [ 0.0000,  1.9475,  1.1275,  0.7542, -1.0869],
         [ 0.0000,  0.0000, -0.7928,  0.2592,  0.9940],
         [ 0.0000,  0.0000,  0.0000,  0.6531,  0.5930],
         [ 0.0000,  0.0000,  0.0000,  0.0000, -2.9251]]))

In [47]:
u, s, v = torch.svd(x)
u, s, v

(tensor([[-0.1143,  0.2046,  0.3895,  0.6376, -0.6220],
         [-0.7705, -0.4955,  0.3389, -0.2124, -0.0270],
         [ 0.3364, -0.4363,  0.4518,  0.4497,  0.5386],
         [-0.2572, -0.3315, -0.7241,  0.5455,  0.0440],
         [-0.4624,  0.6422,  0.0705,  0.2201,  0.5660]]),
 tensor([3.4324, 2.1275, 1.5875, 1.0976, 0.3730]),
 tensor([[-0.5742,  0.5876,  0.3491, -0.3214, -0.3159],
         [-0.4346, -0.5344,  0.5219, -0.1151,  0.4899],
         [ 0.1970, -0.5124,  0.1270, -0.5203, -0.6417],
         [-0.2976, -0.2304,  0.1529,  0.7660, -0.4982],
         [ 0.5950,  0.2312,  0.7525,  0.1611,  0.0163]]))

In [49]:
torch.linalg.qr(x)

torch.return_types.linalg_qr(
Q=tensor([[-0.2246,  0.0629, -0.2120, -0.8241, -0.4707],
        [-0.4800, -0.8568,  0.1488, -0.0355,  0.1098],
        [ 0.4862, -0.4288, -0.4051,  0.2727, -0.5842],
        [ 0.2086, -0.1437, -0.6842, -0.2544,  0.6348],
        [-0.6628,  0.2394, -0.5484,  0.4249, -0.1487]]),
R=tensor([[-2.4275, -0.8242,  0.9699, -0.5191,  1.1581],
        [ 0.0000, -1.8904, -0.6482, -0.9066,  0.8902],
        [ 0.0000,  0.0000,  0.8420, -0.7451,  0.5190],
        [ 0.0000,  0.0000,  0.0000, -0.6614,  0.1436],
        [ 0.0000,  0.0000,  0.0000,  0.0000, -1.8569]]))

## 三、tensor裁剪：
对tensor的值限定最大最小值，并统一替换。对梯度裁剪有用

In [57]:
x=torch.randn(3,3)*10
x

tensor([[ 8.7792e+00, -1.3920e+01, -4.0329e+00],
        [ 1.7280e+01, -2.1355e+01, -1.5609e-02],
        [ 1.0415e+01,  8.0915e+00,  5.2920e+00]])

In [59]:
x=x.clamp(0,10)  #限定最大最小值
x

tensor([[ 8.7792,  0.0000,  0.0000],
        [10.0000,  0.0000,  0.0000],
        [10.0000,  8.0915,  5.2920]])

## 四、筛选填充操作

In [62]:
nz=torch.nonzero(x)  #输出非0元素坐标
nz

tensor([[0, 0],
        [1, 0],
        [2, 0],
        [2, 1],
        [2, 2]])

In [66]:
torch.take(x,torch.tensor([0,1,3,4,5,6,7]))  #将输入x视为1维数据（拉平），然后根据坐标获取相应元素

tensor([ 8.7792,  0.0000, 10.0000,  0.0000,  0.0000, 10.0000,  8.0915])

In [78]:
one=torch.ones(x.shape) #torch.ones_like(x)
one

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [72]:
cd=torch.where(x != 0,x,one)  #对x进行条件筛选，符合条件返回第一个x的值，不符合条件返回one的值
cd

tensor([[ 8.7792,  1.0000,  1.0000],
        [10.0000,  1.0000,  1.0000],
        [10.0000,  8.0915,  5.2920]])

In [76]:
id=torch.index_select(x,dim=0,index=torch.tensor([2,0]))  #将第dim维的数据按照index顺序返回
id

tensor([[10.0000,  8.0915,  5.2920],
        [ 8.7792,  0.0000,  0.0000]])

In [79]:
mask=x.gt(9)
mask

tensor([[False, False, False],
        [ True, False, False],
        [ True, False, False]])

In [82]:
torch.masked_select(x,mask)  #根据mask矩阵筛选True对应的元素并返回

tensor([10., 10.])

## 五、拼接操作

In [4]:
x=torch.randn(2,3)
x

tensor([[-2.5237, -1.3238, -0.5301],
        [ 0.6416,  1.2514, -1.5967]])

In [5]:
y=torch.randn(2,3)
y

tensor([[-0.0861, -0.3447,  0.6793],
        [ 0.2008, -0.7792,  0.0546]])

### 5.1 拼接：维度不会变化

In [7]:
torch.cat((x,y),dim=0)  #在0维上进行拼接

tensor([[-2.5237, -1.3238, -0.5301],
        [ 0.6416,  1.2514, -1.5967],
        [-0.0861, -0.3447,  0.6793],
        [ 0.2008, -0.7792,  0.0546]])

In [8]:
torch.cat((x,y),dim=1)  #在0维上进行拼接

tensor([[-2.5237, -1.3238, -0.5301, -0.0861, -0.3447,  0.6793],
        [ 0.6416,  1.2514, -1.5967,  0.2008, -0.7792,  0.0546]])

### 5.2 堆叠：会升维

In [9]:
torch.stack((x,y),dim=0)  #在0维上进行拼接

tensor([[[-2.5237, -1.3238, -0.5301],
         [ 0.6416,  1.2514, -1.5967]],

        [[-0.0861, -0.3447,  0.6793],
         [ 0.2008, -0.7792,  0.0546]]])

In [10]:
torch.stack((x,y),dim=1)  #在1维上进行拼接

tensor([[[-2.5237, -1.3238, -0.5301],
         [-0.0861, -0.3447,  0.6793]],

        [[ 0.6416,  1.2514, -1.5967],
         [ 0.2008, -0.7792,  0.0546]]])

In [11]:
torch.stack((x,y),dim=2)  #在2维上进行拼接

tensor([[[-2.5237, -0.0861],
         [-1.3238, -0.3447],
         [-0.5301,  0.6793]],

        [[ 0.6416,  0.2008],
         [ 1.2514, -0.7792],
         [-1.5967,  0.0546]]])

## 六、切片（矩阵分块）

In [18]:
a=torch.randn(9,4)
a

tensor([[-0.6574, -0.8669,  1.0812,  0.8035],
        [-0.9865, -0.0931, -1.3961, -1.0793],
        [ 0.4314, -0.5700,  0.3104,  1.2105],
        [ 0.2011, -1.3524, -0.9428, -0.2014],
        [-1.8500, -0.1605, -1.6803, -0.8099],
        [-0.7084, -0.1085,  2.4976,  0.8180],
        [-0.4252,  1.0747, -0.7570, -0.1357],
        [ 1.1663, -0.2940, -1.6488, -1.0926],
        [ 1.0824, -0.3400,  0.5469,  0.0564]])

In [24]:
torch.chunk(a,2,dim=0)  #在0维上切片，无法整除将导致最后一个tensor的数量小于均值（余数）

(tensor([[-0.6574, -0.8669,  1.0812,  0.8035],
         [-0.9865, -0.0931, -1.3961, -1.0793],
         [ 0.4314, -0.5700,  0.3104,  1.2105],
         [ 0.2011, -1.3524, -0.9428, -0.2014],
         [-1.8500, -0.1605, -1.6803, -0.8099]]),
 tensor([[-0.7084, -0.1085,  2.4976,  0.8180],
         [-0.4252,  1.0747, -0.7570, -0.1357],
         [ 1.1663, -0.2940, -1.6488, -1.0926],
         [ 1.0824, -0.3400,  0.5469,  0.0564]]))

In [20]:
torch.chunk(a,2,dim=1)

(tensor([[-0.6574, -0.8669],
         [-0.9865, -0.0931],
         [ 0.4314, -0.5700],
         [ 0.2011, -1.3524],
         [-1.8500, -0.1605],
         [-0.7084, -0.1085],
         [-0.4252,  1.0747],
         [ 1.1663, -0.2940],
         [ 1.0824, -0.3400]]),
 tensor([[ 1.0812,  0.8035],
         [-1.3961, -1.0793],
         [ 0.3104,  1.2105],
         [-0.9428, -0.2014],
         [-1.6803, -0.8099],
         [ 2.4976,  0.8180],
         [-0.7570, -0.1357],
         [-1.6488, -1.0926],
         [ 0.5469,  0.0564]]))

In [27]:
torch.split(a,2,dim=0)   #split和chunk功能相似，但传入的第二个参数是维度size。这里值0维每2个元素切分一次

(tensor([[-0.6574, -0.8669,  1.0812,  0.8035],
         [-0.9865, -0.0931, -1.3961, -1.0793]]),
 tensor([[ 0.4314, -0.5700,  0.3104,  1.2105],
         [ 0.2011, -1.3524, -0.9428, -0.2014]]),
 tensor([[-1.8500, -0.1605, -1.6803, -0.8099],
         [-0.7084, -0.1085,  2.4976,  0.8180]]),
 tensor([[-0.4252,  1.0747, -0.7570, -0.1357],
         [ 1.1663, -0.2940, -1.6488, -1.0926]]),
 tensor([[ 1.0824, -0.3400,  0.5469,  0.0564]]))

In [30]:
torch.split(a,[3,6],dim=0)  #按照list中的size切分，list的和必须等于维度的size

(tensor([[-0.6574, -0.8669,  1.0812,  0.8035],
         [-0.9865, -0.0931, -1.3961, -1.0793],
         [ 0.4314, -0.5700,  0.3104,  1.2105]]),
 tensor([[ 0.2011, -1.3524, -0.9428, -0.2014],
         [-1.8500, -0.1605, -1.6803, -0.8099],
         [-0.7084, -0.1085,  2.4976,  0.8180],
         [-0.4252,  1.0747, -0.7570, -0.1357],
         [ 1.1663, -0.2940, -1.6488, -1.0926],
         [ 1.0824, -0.3400,  0.5469,  0.0564]]))

## 七、变形reshape和转换

In [40]:
a=torch.randn(3,4, 2)
a

tensor([[[-0.0999,  1.5645],
         [ 0.8376, -1.5407],
         [-0.0216, -1.0076],
         [-0.2789,  0.8097]],

        [[-1.1215, -0.7736],
         [ 1.1860,  0.5838],
         [ 0.6006, -0.3323],
         [-0.4777, -0.8933]],

        [[-1.7903, -0.0980],
         [-0.7409, -0.4019],
         [-0.3832,  0.7117],
         [-0.1288,  1.1535]]])

In [54]:
a1=a.reshape(-1,24)  #reshape
a1

tensor([[-0.0999,  1.5645,  0.8376, -1.5407, -0.0216, -1.0076, -0.2789,  0.8097,
         -1.1215, -0.7736,  1.1860,  0.5838,  0.6006, -0.3323, -0.4777, -0.8933,
         -1.7903, -0.0980, -0.7409, -0.4019, -0.3832,  0.7117, -0.1288,  1.1535]])

In [43]:
b=torch.randn(3,4)

In [45]:
torch.t(b)  #转置,仅对2-d tensor操作

tensor([[ 0.1489, -0.4377, -0.4256],
        [ 1.2151,  0.3132, -0.5961],
        [ 1.7680,  0.8465, -0.1739],
        [-0.5731, -0.7933,  0.7739]])

In [46]:
torch.transpose(a,0,2)

tensor([[[-0.0999, -1.1215, -1.7903],
         [ 0.8376,  1.1860, -0.7409],
         [-0.0216,  0.6006, -0.3832],
         [-0.2789, -0.4777, -0.1288]],

        [[ 1.5645, -0.7736, -0.0980],
         [-1.5407,  0.5838, -0.4019],
         [-1.0076, -0.3323,  0.7117],
         [ 0.8097, -0.8933,  1.1535]]])

In [57]:
torch.squeeze(a1) #去除维度size为1的维度

tensor([-0.0999,  1.5645,  0.8376, -1.5407, -0.0216, -1.0076, -0.2789,  0.8097,
        -1.1215, -0.7736,  1.1860,  0.5838,  0.6006, -0.3323, -0.4777, -0.8933,
        -1.7903, -0.0980, -0.7409, -0.4019, -0.3832,  0.7117, -0.1288,  1.1535])

In [58]:
torch.unbind(a,dim=1) #删除某个维度

(tensor([[-0.0999,  1.5645],
         [-1.1215, -0.7736],
         [-1.7903, -0.0980]]),
 tensor([[ 0.8376, -1.5407],
         [ 1.1860,  0.5838],
         [-0.7409, -0.4019]]),
 tensor([[-0.0216, -1.0076],
         [ 0.6006, -0.3323],
         [-0.3832,  0.7117]]),
 tensor([[-0.2789,  0.8097],
         [-0.4777, -0.8933],
         [-0.1288,  1.1535]]))

In [62]:
torch.unsqueeze(b,1) #在指定位置添加维度

tensor([[[ 0.1489,  1.2151,  1.7680, -0.5731]],

        [[-0.4377,  0.3132,  0.8465, -0.7933]],

        [[-0.4256, -0.5961, -0.1739,  0.7739]]])

In [75]:
torch.flip(a,[0,2]) #对指定维度反转tensor（倒序）,这里先对0维倒序，在对2维倒序

tensor([[[-0.0980, -1.7903],
         [-0.4019, -0.7409],
         [ 0.7117, -0.3832],
         [ 1.1535, -0.1288]],

        [[-0.7736, -1.1215],
         [ 0.5838,  1.1860],
         [-0.3323,  0.6006],
         [-0.8933, -0.4777]],

        [[ 1.5645, -0.0999],
         [-1.5407,  0.8376],
         [-1.0076, -0.0216],
         [ 0.8097, -0.2789]]])

In [81]:
torch.rot90(a,1,[0,2])  #对指定维度旋转tensor 90度。如果k大于0，则表示逆时针旋转；如果k小于0，则表示顺时针旋转。

tensor([[[ 1.5645, -0.7736, -0.0980],
         [-1.5407,  0.5838, -0.4019],
         [-1.0076, -0.3323,  0.7117],
         [ 0.8097, -0.8933,  1.1535]],

        [[-0.0999, -1.1215, -1.7903],
         [ 0.8376,  1.1860, -0.7409],
         [-0.0216,  0.6006, -0.3832],
         [-0.2789, -0.4777, -0.1288]]])

## 八、填充操作

In [83]:
torch.full([2,3],3.14)  #使用一个值填充一个tensor

tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])

## 九、并行

In [12]:
torch.get_num_threads()  #获取当前并行化的线程数

16

In [13]:
torch.set_num_threads(5) #设置并行数

In [14]:
torch.get_num_threads()

5

## 十、与numpy互换

In [16]:
a=torch.randn(3,4, 2)
a

tensor([[[ 0.4149,  1.5135],
         [ 3.5197, -0.6032],
         [-1.7820,  1.3305],
         [ 0.3037,  1.0197]],

        [[-1.5207, -0.7825],
         [ 1.2652, -0.2896],
         [-0.1404, -1.2571],
         [ 2.6061, -2.4921]],

        [[-0.5974, -0.4204],
         [-1.1530,  0.7644],
         [-1.2318, -0.2161],
         [ 1.1418,  0.6244]]])

In [17]:
a.numpy()

array([[[ 0.4149176 ,  1.5135244 ],
        [ 3.5197093 , -0.603231  ],
        [-1.7820241 ,  1.3304595 ],
        [ 0.3036727 ,  1.0197457 ]],

       [[-1.5207468 , -0.7825281 ],
        [ 1.2652346 , -0.28959903],
        [-0.14037289, -1.257089  ],
        [ 2.6061137 , -2.4920948 ]],

       [[-0.5974247 , -0.42040733],
        [-1.152967  ,  0.7644146 ],
        [-1.2317884 , -0.2161485 ],
        [ 1.1418033 ,  0.6244068 ]]], dtype=float32)

In [18]:
# torch.from_numpy()  #从numpy对象转为tensor