In [4]:
import numpy as np
data=np.genfromtxt(r'E:\python_study\untitled\数据挖掘与机器学习\data.txt',delimiter=',',dtype=str)
print(data.dtype)

<U52


In [7]:
npary=np.array([[1,2,3],['4.0',5,6],[7,8,9]])
print(npary.dtype.name)

str352


In [11]:
a=(data[:,2]=='Viet Nam')
data[a,:]

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1985', 'Western Pacific', 'Viet Nam', 'Spirits', '0.05'],
       ['1987', 'Western Pacific', 'Viet Nam', 'Beer', '0.11'],
       ['1987', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1989', 'Western Pacific', 'Viet Nam', 'Spirits', '0.03'],
       ['1985', 'Western Pacific', 'Viet Nam', 'Beer', '0.12'],
       ['1984', 'Western Pacific', 'Viet Nam', 'Beer', '0.13'],
       ['1986', 'Western Pacific', 'Viet Nam', 'Other', ''],
       ['1987', 'Western Pacific', 'Viet Nam', 'Other', '']], dtype='<U52')

In [10]:
data[2]

array(['1986', 'Americas', 'Uruguay', 'Other', '0.5'], dtype='<U52')

In [10]:
np.linspace(0,9,10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [12]:
np.random.random((2,3))

array([[0.61106432, 0.12374456, 0.54471636],
       [0.47753222, 0.19566581, 0.88401253]])

In [13]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

In [15]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [16]:
z=np.array([[5,6,7],[7,8,9]])
x.dot(z)

array([[19, 22, 25],
       [43, 50, 57]])

In [17]:
z.dot(x)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [3]:
import os
print(os.getpid(),os.getppid())

7380 8004


In [1]:
import numpy as np
np.logspace(1,10,10,endpoint=True,base=10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [2]:
a='abcd'
np.fromstring(a,dtype=np.int8)

D:\Users\msi\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  


array([ 97,  98,  99, 100], dtype=int8)

In [6]:
a=np.arange(10,60,10).reshape((-1,1))+np.arange(0,6,1)
a[(1,2,3),(3,4,5)]

array([23, 34, 45])

In [8]:
np.ones_like(a)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [1]:
print(123)

123
